### PR TITLE
support bare metal toolchains

### LINKED ISSUE #343: ld.bfd: unrecognized option --exclude-libs
```
CROSS_COMPILE=riscv64-elf- make -C build/opensbi PLATFORM=generic FW_TEXT_START=0x40000000 FW_OPTIONS=0
 ELF       platform/generic/firmware/payloads/test.elf
/usr/lib/gcc/riscv64-elf/12.2.0/../../../../riscv64-elf/bin/ld.bfd: unrecognized option '--exclude-libs'
/usr/lib/gcc/riscv64-elf/12.2.0/../../../../riscv64-elf/bin/ld.bfd: use the --help option for usage information
collect2: error: ld returned 1 exit status
```

Is this because the toolchain is for bare-metal?
Should the toolchain be checked before `--exclude-libs` is added to `ELFFLAGS`?

### PR DESCRIPTION
**Pull request by yogo1212**
This addresses the issues that
- ld.bfd doesn't support `--exclude-libs`
- and there exists no `dynsym` section
with `riscv64-elf-`.

Fixes #343.

### CODE REVIEW

**Comment by yogo1212** [comment]
don't know what i did there just now.
hunk was missing from commit, make saw the changed file, git didn't - fixed now.

**Comment by avpatel** [comment]
We have mailing list based patch review so it would be great if you can send these patchs to OpenSBI mailing list.

You need to join OpenSBI mailing list using following link
http://lists.infradead.org/mailman/listinfo/opensbi

Make sure you use "git send-email" to send the patches.

Regards,
Anup

**Comment by egeKeyvan** [comment]
These changes also fixed the same problem that I had on MacOS Ventura. Is it possible for this patch to be merged ?

**Comment by yogo1212** [comment]
@egeKeyvan the check for the option was merged.
are you talking about the dynsym removal?

**Comment by egeKeyvan** [comment]
> @egeKeyvan the check for the option was merged.
> are you talking about the dynsym removal?

I was talking about the dynsym removal. Without it, I had the problems of the #343

**Pull request closed without merging**
